import './globals.css';

export const metadata = {
  title: '{{appName}}',
  description: 'Generated by poudwal',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
